inputSet:
  name: Build_aws_vpc_configuration_1720103295039-pr-trigger-input-set
  identifier: Build_aws_vpc_configuration_1720103295039prtriggerinputset
  orgIdentifier: default
  projectIdentifier: myfirstproject
  pipeline:
    identifier: Build_aws_vpc_configuration_1720103295039
    properties:
      ci:
        codebase:
          build:
            type: PR
            spec:
              number: <+trigger.prNumber>
