inputSet:
  name: Build_aws_vpc_configuration_1720103295039-push-trigger-input-set
  identifier: Build_aws_vpc_configuration_1720103295039pushtriggerinputset
  orgIdentifier: default
  projectIdentifier: myfirstproject
  pipeline:
    identifier: Build_aws_vpc_configuration_1720103295039
    properties:
      ci:
        codebase:
          build:
            type: branch
            spec:
              branch: <+trigger.branch>
